<?php
/*
 * hook_ctools_plugin_api
 */
function context_respect_ctools_plugin_api($module, $api) {
  if ($module == 'context' && $api == 'plugins') {
    return array('version' => 3);
  }
}

/*
 * hook_context_plugins
 */
function context_respect_context_plugins() {
  $plugins['context_respect_reaction_block'] = array(
    'handler' => array(
      'path' => drupal_get_path('module', 'context_respect') . '/plugins',
      'file' => 'context_respect_reaction_block.inc',
      'class' => 'context_respect_reaction_block',
      'parent' => 'context_reaction',
    ),
  );
  
  return $plugins;
}

/*
 * hook_context_registry_alter
 */
function context_respect_context_registry_alter(&$registry) {
  if (!empty($registry['reactions']['block'])) {
    $registry['reactions']['block']['plugin'] = 'context_respect_reaction_block';
  }
}